<?php if(isset($_layoutParams['js']) && count($_layoutParams['js']))
    for($i=0;$i<count($_layoutParams['js']);$i++)
        echo      "<script src='". $_layoutParams['js'][$i]."'></script>";
?>


<!-- /HEADER -->


<!-- XXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx aquie va  -->

<div class="container">

    <!-- SECTION -->
    <div class="container">
    <div class="section" id="todo">
    </div>



<div class="container">

    <!-- row -->
   <div id="lista_negocios">
    <?php
       echo $this->lista_negocios;
       ?>
   </div>
    <!-- /row -->


</div>
    </div>
    <!-- /SECTION -->
    <!-- esto es lo den medio-->
</div>
<!-- /container -->

<script>
    $("#btbuscar").click(function () {
        var parametro=$("#cjclave").val();
        $.ajax({
            url:"index/obtenerNegocios2/"+parametro,
            success:function (data) {
                $("#lista_negocios").html(data);
            }
        });
    });
</script>