<br>
<div class="card card-register">
    <div class="card-header text-center"><h1 class="text-info">Crea una cuenta Gratuita</h1></div>
    <div class="card-body">
        <form>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-3">
                        <label for="exampleInputName">Primer Nombre</label>
                        <input class="form-control" id="exampleInputName" type="text" aria-describedby="nameHelp" placeholder="Primer Nombre">
                    </div>
                    <div class="col-md-3">
                        <label for="exampleInputLastName">Segundo Nombre</label>
                        <input class="form-control" id="exampleInputName2" type="text" aria-describedby="nameHelp" placeholder="Segundo Nombre">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-3">
                        <label for="exampleInputName">Primer Apellido</label>
                        <input class="form-control" id="exampleInputLastName" type="text" aria-describedby="nameHelp" placeholder="Primer Apellido">
                    </div>
                    <div class="col-md-3">
                        <label for="exampleInputLastName">Segundo Apellido</label>
                        <input class="form-control" id="exampleInputLastName2" type="text" aria-describedby="nameHelp" placeholder="Segundo Apellido">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-3">
                        <label for="exampleInputName">Cedula</label>
                        <input class="form-control" id="exampleInputCedula" type="text" aria-describedby="nameHelp" placeholder="Cedula de Identidad">
                    </div>
                    <div class="col-md-3">
                        <label for="exampleInputLastName">Telefono</label>
                        <input class="form-control" id="exampleInputTelefono" type="text" aria-describedby="nameHelp" placeholder="Telefono">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-3">
                        <label for="exampleInputName">Direccion</label>
                        <input class="form-control" id="exampleInputDireccion" type="text" aria-describedby="nameHelp" placeholder="Direccion">
                    </div>
                    <div class="col-md-3">
                        <label for="exampleInputLastName">Genero</label>
                        <input class="form-control" id="exampleInputGenero" type="text" aria-describedby="nameHelp" placeholder="Genero">
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="exampleInputPassword1">Contrase&ntildea</label>
                                <input class="form-control" id="exampleInputPassword1" type="password" placeholder="Contraseña">
                            </div>
                            <div class="col-md-6">
                                <label for="exampleConfirmPassword">Confirmar Contrase&ntildea</label>
                                <input class="form-control" id="exampleConfirmPassword" type="password" placeholder="Confirmar Contraseña">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-3">
                        <label for="exampleInputName">Nombre de Usuario</label>
                        <input class="form-control" id="exampleInputusername" type="text" aria-describedby="nameHelp" placeholder="Usuario">
                    </div>
                    <div class="col-md-3">
                        <label for="exampleInputLastName">Clave</label>
                        <input class="form-control" id="exampleInputClave" type="text" aria-describedby="nameHelp" placeholder="Clave">
                    </div>

                    <div class="form-row">
                        <div class="col-md-3">
                            <label for="exampleInputEmail1">Correo Electronico</label>
                            <input class="form-control" id="exampleInputEmail1" type="email" aria-describedby="emailHelp" placeholder="Correo Electronico">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-md-3">
                            <label for="exampleInputEmail1">Imagen Banner</label>
                            <input class="" id="exampleInputBanner" type="file" aria-describedby="emailHelp" placeholder="Correo Electronico">
                        </div>
                    </div>

                </div>

            </div>



            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-4 col-lg-offset-4">
                        <br>
                        <button type="button" class="btn btn-primary btn-block" >Registrar</button>
                        <br>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>