
<!-- SECTION -->
<div class="container">
    <div class="section col-md-6">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <img src="<?php echo $_layoutParams['ruta_img'];?>banner_default.jpg" alt="">


            <br>








            <div class="container">

                <div class="row">
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img class="card-img-top" src="<?php echo $_layoutParams['ruta_img'];?>loc.jpg" alt="Card image cap">


                            <span class="glyphicon glyphicon-location"></span>
                            <div class="alert-info">
                                <p class="alert-info">Busquenos: De donde fue la Policia 2 c al O</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img class="card-img-top" src="<?php echo $_layoutParams['ruta_img'];?>tel.png" alt="Card image cap">
                            <div class="alert-info">
                                <p class="alert-info">Llamenos al 84210198</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img class="card-img-top" src="<?php echo $_layoutParams['ruta_img'];?>des.png" alt="Card image cap">
                            <div class="alert-info">
                                <p class="alert-info">Descripcion: Le ofrecemos abarrotes</p><p> en General, lacteos, poteria y todo lo del hogar</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="container">
                <di></di>
            </div>











            <center><h1>Productos</h1></center>

            <!-- Products tab & slick -->
            <div class="col-md-12">
                <div class="row">
                    <div class="products-tabs">
                        <!-- tab -->
                        <div id="tab2" class="tab-pane fade in active">
                            <div class="products-slick" data-nav="#slick-nav-2">

                                <!-- product -->

                                <!-- /product -->



                                <div class='col-md-4 col-xs-6'>
                                    <div class='shop'>
                                        <div class='shop-img'>
                                            <img src='<?php echo $_layoutParams['ruta_img'];?>pro1.jpg' alt=''>
                                        </div>
                                        <div class='shop-body'>
                                            <h4>Precio:C$ 12</h4>
                                            <h5>Descripcion: Producto Consumible</h5>

                                        </div>
                                    </div>
                                </div>



                                <div class='col-md-4 col-xs-6'>
                                    <div class='shop'>
                                        <div class='shop-img'>
                                            <img src='<?php echo $_layoutParams['ruta_img'];?>pro2.jpg' alt=''>
                                        </div>
                                        <div class='shop-body'>
                                            <h4>Precio:C$ 10</h4>
                                            <h5>Descripcion: Producto Consumible</h5>

                                        </div>
                                    </div>
                                </div>


                                <div class='col-md-4 col-xs-6'>
                                    <div class='shop'>
                                        <div class='shop-img'>
                                            <img src='<?php echo $_layoutParams['ruta_img'];?>pro3.jpg' alt=''>
                                        </div>
                                        <div class='shop-body'>
                                            <h4>Precio:C$ 10</h4>
                                            <h5>Descripcion: Producto Consumible</h5>

                                        </div>
                                    </div>
                                </div>

                            </div>




                        </div>
                        <div id="slick-nav-2" class="products-slick-nav"></div>
                    </div>
                    <!-- /tab -->
                </div>
            </div>
        </div>

        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<br>
<!-- /SECTION -->
<!-- esto es lo den medio-->
</div>
<!-- /container -->