<style>

    .btn-file {
        position: relative;
        overflow: hidden;
    }
    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
    }


</style>
<div class="container">
    <br>
    <div class="card card-register">
        <div class="card-header text-center"><h1 class="text-info">Crea una cuenta Gratuita</h1></div>
        <div class="card-body">
            <form>
                <div class="form-group">


                </div>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-3">
                            <label for="Name">Nombre y Apellido</label>
                            <input name="nombre" class="form-control" id="Nombre" type="text" aria-describedby="nameHelp" placeholder="Nombre Completo">
                        </div>
                        <div class="col-md-3">
                            <label for="LastName">Cedula</label>
                            <input name="cedula" class="form-control" id="Cedula" type="text" aria-describedby="nameHelp" placeholder="Cedula">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-3">
                            <label for="Name">Direccion</label>
                            <input class="form-control" id="Direccion" type="text" aria-describedby="nameHelp" placeholder="Direccion">
                        </div>
                        <div class="col-md-3">
                            <label for="LastName">Genero</label>
                           <select class="form-control" id="Genero" type="text" aria-describedby="nameHelp" placeholder="Genero">
                               <option value="M">Masculino</option>
                               <option value="F">Femenino</option>
                           </select>

                        </div>

                    </div>
                    <div class="form-row">
                        <div class="col-md-3">
                            <label for="Name">Nombre de Usuario</label>
                            <input class="form-control" id="username" type="text" aria-describedby="nameHelp" placeholder="Usuario">
                        </div>
                        <div class="col-md-3">
                            <label for="LastName">Clave</label>
                            <input class="form-control" id="Clave" type="password" aria-describedby="nameHelp" placeholder="Clave">
                        </div>

                        <div class="form-row">
                            <div class="col-md-3">
                                <label for="Email1">Correo Electronico</label>
                                <input class="form-control" id="Email1" type="email" aria-describedby="emailHelp" placeholder="Correo Electronico">
                            </div>
                        </div>

                        <div class="col-md-3">
                            <label for="LastName">Telefono</label>
                            <input class="form-control" id="Telefono" type="text" aria-describedby="nameHelp" placeholder="Telefono">
                        </div>

                    </div>

                </div>



                <div class="form-row">
                    <div class="form-group">
                        <div class="col-md-4 col-lg-offset-4">
                            <br>
                            <button id="btregistro" type="button" class="btn btn-primary btn-block" >Registrar</button>
                            <br>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /container -->
<script>
    $("#btregistro").click(function () {

        var nombre=$("#Nombre").val();
        var cedula=$("#Cedula").val();
        var direccion=$("#Direccion").val();
        var genero=$("#Genero").val();
        var usuario=$("#username").val();
        var pass=$("#Clave").val();
        var email=$("#Email1").val();
        var telefono=$("#Telefono").val();


        $.ajax({
            url:"registro/registrar",
            data:{'nombre':nombre,'cedula':cedula,'direccion':direccion,'genero':genero,'usuario':usuario,'pass':pass,'email':email,'telefono':telefono},
            type:"post",
            success:function (data) {
                window.open('registro/auntenticar/'+data,"_self");
            }
        })
    });
</script>