<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
    <li><a data-toggle="tab" href="#mperfil">Perfil</a></li>
    <li><a data-toggle="tab" href="#mnegocio">Negocio</a></li>
    <li><a data-toggle="tab" href="#mproductos">Productos</a></li>
    <li><a data-toggle="tab" href="#meventos">Eventos</a></li>
    <li><a data-toggle="tab" href="#mpromociones">Promociones</a></li>
</ul>

<div class="tab-content">
    <div id="home" class="tab-pane fade in active">
        <h3>Perfil</h3>
        <p>Datos Principales.</p>
    </div>
    <div id="#mperfil" class="tab-pane fade">
        <h3>Perfil del Comerciante</h3>
        <p>perfil comerciante</p>
    </div>
    <div id="#mnegocio" class="tab-pane fade">
        <h3>Negocio</h3>




        <br>
        <div class="card card-register">
            <div class="card-header text-center"><h1 class="text-info">Registra Tu Negocio</h1></div>
            <div class="card-body">
                <form>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-3">
                                <label for="Nom">Negocio</label>
                                <input class="form-control" name="nom" id="Nom" type="text" aria-describedby="nameHelp" placeholder="Nombre del Negocio">
                            </div>
                            <div class="col-md-3">
                                <label for="tel">Telefono</label>
                                <input class="form-control" name="tel" id="tel" type="text" aria-describedby="nameHelp" placeholder="Telefono">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-3">
                                <label for="dir">Direccion</label>
                                <input class="form-control" name="dir" id="dir" type="text" aria-describedby="nameHelp" placeholder="Direccion">
                            </div>
                            <div class="col-md-3">
                                <label for="des">Descripcion</label>
                                <input class="form-control" iname="des" id="des" type="text" aria-describedby="nameHelp" placeholder="Descripcion">
                            </div>
                            <div class="form-row">
                                <div class="col-md-3">
                                    <label for="portada">Portada</label>
                                    <input class="" name="portada" id="portada" type="file" aria-describedby="emailHelp" placeholder="Portada">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-3">
                                <label for="ced">Valoracion</label>
                                <input class="form-control" name="val" id="val" type="text" aria-describedby="nameHelp" placeholder="Valoracion">
                            </div>
                            <div class="col-md-3">
                                <label for="lat">Latitud</label>
                                <input class="form-control" name="lat" id="lat" type="text" aria-describedby="nameHelp" placeholder="Latitud">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-3">
                                <label for="long">Longitud</label>
                                <input class="form-control" name="long" id="long" type="text" aria-describedby="nameHelp" placeholder="Longitud">
                            </div>
                            <div class="col-md-3">
                                <label for="horap">Horario de Apertura</label>
                                <input class="form-control" name="horap" id="horap" type="text" aria-describedby="nameHelp" placeholder="horario de Apertura">
                            </div>
                            <div class="col-md-3">
                                <label for="horac">Horario de Cierre</label>
                                <input class="form-control" name="horac" id="horac" type="text" aria-describedby="nameHelp" placeholder="horario de Cierre">
                            </div>
                        </div>
                    </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <div class="col-md-4 col-lg-offset-4">
                        <br>
                        <button type="button" class="btn btn-primary btn-block" >Registrar</button>
                        <br>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
    </div>

    <div id="#mproductos" class="tab-pane fade">
        <h3>Lista de Productos</h3>

    </div>

    <div id="#meventos" class="tab-pane fade">
        <h3>Eventos</h3>

    </div>

    <div id="#mpromociones" class="tab-pane fade">
        <h3>Promociones</h3>

    </div>

</div>





