
<style>
    /* Always set the map height explicitly to define the size of the div
     * element that contains the map. */
    #map {
        height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {

     height: 90%;
        margin: 0;
        padding: 0;

    }
    #map{

    }
</style>

<!-- /HEADER -->
<div class="clear"></div>
<div id="map" style=""></div>



<script>
    $("#btbuscar").click(function () {

        //  $("#map").html("");
        initMap();
    });
    var customLabel = {
        restaurant: {
            label: 'R'
        },
        bar: {
            label: 'B'
        }
    };

    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            center: new google.maps.LatLng(13.638029, -86.472541),
            zoom: 15
        });
        var infoWindow = new google.maps.InfoWindow;


        var parametro=$("#cjclave").val();


        //downloadUrl('localhost/tiangue/public/mapa.php?clave='+parametro, function(data) {
        downloadUrl('<?php echo BASE_URL; ?>public/mapa.php?clave='+parametro, function(data) {
            var xml = data.responseXML;
            var markers = xml.documentElement.getElementsByTagName('marker');
            Array.prototype.forEach.call(markers, function(markerElem) {
                var id = markerElem.getAttribute('id');
                var name = markerElem.getAttribute('name');
                var address = markerElem.getAttribute('address');
                var type = markerElem.getAttribute('type');
                var point = new google.maps.LatLng(
                    parseFloat(markerElem.getAttribute('lat')),
                    parseFloat(markerElem.getAttribute('lng')));

                var infowincontent = document.createElement('div');
                var strong = document.createElement('strong');
                strong.textContent = name
                infowincontent.appendChild(strong);
                infowincontent.appendChild(document.createElement('br'));

                var text = document.createElement('text');
                text.textContent = address
                infowincontent.appendChild(text);
                var icon = customLabel[type] || {};
//icon = 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'

                var icon="";
                var f=new Date();
                if( markerElem.getAttribute('abre')>= f.getHours() && markerElem.getAttribute('abre')<= f.getHours())
                    icon='http://maps.google.com/mapfiles/ms/icons/green-dot.png';
                else
                    icon='http://maps.google.com/mapfiles/ms/icons/red-dot.png';

                var marker = new google.maps.Marker({
                    map: map,
                    position: point,
                    icon : icon,
                    label: icon.label
                });
                marker.addListener('click', function() {
                    infoWindow.setContent(infowincontent);
                    infoWindow.open(map, marker);
                });
            });
        });
    }


    function downloadUrl(url, callback) {
        var request = window.ActiveXObject ?
            new ActiveXObject('Microsoft.XMLHTTP') :
            new XMLHttpRequest;

        request.onreadystatechange = function() {
            if (request.readyState == 4) {
                request.onreadystatechange = doNothing;
                callback(request, request.status);
            }
        };

        request.open('GET', url, true);
        request.send(null);
    }

    function doNothing() {}


</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3T6E6kSSwGNbqxN-OXOI1wfnghgd40JQ&callback=initMap">
</script>